# File MAP:
# -------------------------------------------------
# PART 1: Parameters for COM and SWEEP
# -------------------------------------------------
# -------------------------------------------------
# PART 2: Useful Functions
# -------------------------------------------------
# -------------------------------------------------
# PART 3: Identification of instruments
# -------------------------------------------------
# -------------------------------------------------
# PART 4: Functions for DMM
# -------------------------------------------------
# -------------------------------------------------
# PART 5: Functions for uController Phase Shift
# -------------------------------------------------
# -------------------------------------------------
# PART 6: Functions for HV power supply
# -------------------------------------------------
# -------------------------------------------------
# PART 7: Functions for Oscilloscope
# -------------------------------------------------
# -------------------------------------------------
# PART 8: MAIN function
# -------------------------------------------------
# Version avec paramètres centralisés
# Oscillo piloté
# Modifs balayage tension HV
# 2 multimètres
# --------------------------
# Open Power Tuesday - v1.5
# Jan 14th 2024
# Author: Nicolas ROUGER, Luiz VILLA, Joseph KEMDENG, Pauline KERGUS, Matthieu MASSON, Lorenzo LEIJNEN
#
# Joint effort: LAPLACE + LAAS + Owntech -- thanks to all other contributors!
#
# Edit, cleaning and added functions compared to v1.2
# License: GPL 3.0
#
# -------------------------------------------------
# In this version, the Triggers for oscilloscope and DMMs are:
#   Oscillo: Segmented memory, trig on one channel, timeout of 100 ms
#   DMMs: Each DMM is auto-triggered. Idc and Vdc measurements are out of phase
# -> oscillo and both DMM are not synchronized.
# -> an additional (separate) function is provided to align Idc and Vdc afterwards
# -> (thanks Lorenzo!)
# -------------------------------------------------
#
# PURPOSE:
# Opposition method // control and measure 2 half bridges in opposition method
# for losses measurement.
#
# Supervisor to control:
#   1) microcontroller (Spin board from Owntech)
#   2) Power supply
#   3) Digital Multimeters (DMM)
#   4) Oscilloscope
#
# Test sequence is:
#   1) Config microcontroller and turn ON gate signal
#   2) Start logging DC current and DC voltage at 2xDMMs
#   3) Sweep DC bus Voltage (ramp up)
#   4) Sweep Phase Shift generated by microcontroller (ramp up and down)
#   5) Ramp down DC bus Voltage
#   6) Read Buffer of DMMs
#   7) Plot and export data in .csv with timestamp
#   8) Return to initial state
# -------------------------------------------------
#
# REQUIREMENTS:
# SPIN must be loaded with v1.0.0-rc-power_tuesday branch
# The python files with key functions for SPIN must be copied in the "comm_protocol" folder
#   > The folder is located in the cloned GIT repo. at owntech\lib\USB\comm_protocol
# The DMMs used are SDM3065 from Siglent
# The power supply used is Z650+ from TDK Lambda
# The oscilloscope is SDS2000X+ or SDS2000X HD from Siglent
# -------------------------------------------------

import serial
import os
import sys

import serial.serialutil
parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../"))
sys.path.insert(0, parent_dir)


from comm_protocol.src import find_devices
from comm_protocol.src.Shield_Class import Shield_Device

import matplotlib.pyplot as plt
import matplotlib.animation as animation

import xmlrpc.client as xml
import time
import matplotlib.pyplot as plt
import numpy as np
from typing import cast, Any

import os
from matplotlib import pyplot as plt
import pyvisa as visa
from pyvisa import constants
from pyvisa.resources.serial import SerialInstrument

import math

import pylab as pl 
import struct 
import gc

from datetime import datetime

import lib.Oscillo_v1b as controloscillo

# -------------------------------------------------
# PART 1: Parameters for COM and SWEEP
# -------------------------------------------------
delay = 0.1 #delay in seconds (100 ms)
delay2 = 0.2 #delay in seconds (200 ms)
delay3 = 0.2 #delay in seconds for cooldown during phase shift sweep
delay_com = 0.1 # For SPIN BOARD!!!

# PWM parameters
DutyPWM = 0.485 # 48.5%   1 <> 100% duty. Must consider the deadtime and freq values for dead time compensation!
frequencyPWM = 100e3 #100 kHz switching frequency
DeadTimePWM = 300 #ns, deadtime
InitialPhaseShiftPWM = 150 #15° initial & final phase shift between Leg1 and Leg2


# Sweep conditions:
VoltageLimit = 100 # MAX DC Voltage
CurrentLimit = 0.3 # MAX DC Current
VoltageWrite = 50 # Voltage ramp DC voltage value
timestep = 0.1 # delay between each DC voltage value during ramp in seconds
voltage_step = 1 # Voltage step during ramp
PhaseInit = 15 # Initial Phase for Phase sweep in °
PhaseFinal = 95 # Final Phase of phase sweep in °
PhaseStep = 10 # Phase step value during sweep in °

#Duty Sweep
DutyInit = 485 # Initial duty for duty sweep *100 pour avoir un int range 
DutyFinal = 495 # Final duty for duty sweep
DutyStep = 1 # Duty step for duty sweep


# CREATE ONLY A SINGLE RESOURCE MANAGER INSTANCE
rm = visa.ResourceManager()


# Instruments:
# Power Supply
# 'ASRL27::INSTR'
# 'ASRL6::INSTR'
HVpowerSupply = 'ASRL27::INSTR'
#
# DMM for DC Current
#
# SDM3055:
# 'USB0::0xF4EC::0x1206::SDM35HBQ7R1226::INSTR'
#
# SDM3065:
# 
# 'USB0::0xF4EC::0x1203::SDM36HCX800420::INSTR'
# 'USB0::0xF4EC::0x1203::SDM36HCX800421::INSTR'
# DMMforCurrent = 'USB0::0xF4EC::0x1203::SDM36HCX800420::INSTR'
# DMMforVoltage = 'USB0::0xF4EC::0x1203::SDM36HCX800421::INSTR'
DMMforCurrent = 'SDM36HCX800420'
DMMforVoltage = 'SDM36HCX800421'

# DMM for DC Voltage
#
# Oscilloscope
# Oscillo manipe Opposition: 'USB0::0xF4EC::0x1011::SDS2PFFX801302::INSTR'
AddressOSCILLO = 'USB0::0xF4EC::0x1011::SDS2PFFX801302::INSTR'
#AddressOSCILLO = "USB0::0xF4EC::0x1011::SDS2PEEC6R0224::INSTR" 
Sequence = '9' #400 ## At this moment, this is just a number value. No effect on scope
delayOscillo = 0.5

# Used only for history. Not used here!
SaveEachFramePICTURE = 0 #1 for YES, 0 for NO: to save each frame while reading history
SaveEachFrameDATA = 0 #1 for YES, 0 for NO: to save each frame while reading history





# -------------------------------------------------
# PART 5: Functions for uController Phase Shift
# -------------------------------------------------
def SweepPhaseShift(Board,PhaseInit,PhaseFinal,step):
    
    for phase_shift_value in range(PhaseInit, PhaseFinal, step):  # Example values from 0 to 170 with a step of 10
      message1 = Board.sendCommand("PHASE_SHIFT", "LEG2", phase_shift_value)
      print(f"Sent command with phase shift: {phase_shift_value}, message: {message1}")
      # Return to init Phase between each step ?
      #message1 = Board.sendCommand("PHASE_SHIFT", "LEG2", PhaseInit)
      #print(f"Sent command with phase shift: {phase_shift_value}, message: {message1}")
      # Thermal COOLDOWN
      # time.sleep(delay3)

    message1 = Board.sendCommand("PHASE_SHIFT", "LEG2", 360-PhaseInit)
    print(f"Sent command with phase shift: {360-PhaseInit}, message: {message1}")
    
    #for phase_shift_value_down in range(PhaseFinal, PhaseInit-step, -step):  # Example values from 0 to 170 with a step of 10
    #  message1 = Board.sendCommand("PHASE_SHIFT", "LEG2", phase_shift_value_down)
    #  print(f"Sent command with phase shift: {phase_shift_value_down}, message: {message1}")
      # Return to init Phase between each step ?
      #message1 = Board.sendCommand("PHASE_SHIFT", "LEG2", PhaseInit)
      #print(f"Sent command with phase shift: {phase_shift_value}, message: {message1}")
      # Thermal COOLDOWN
      # time.sleep(delay3)


def repeat_get_line(shield, num_times):
    """
    Calls shield.getLine() and prints the result the specified number of times.

    Args:
        shield: The object that has the getLine() method (e.g., Shield).
        num_times (int): The number of times to call getLine() and print the result.
    """
    for _ in range(num_times):
        message = shield.getLine()
        print(message)

# Example usage:
# repeat_get_line(Shield, 5)  # Calls Shield.getLine() 5 times and prints each message




def SweepDutyShift(Board,DutyInit,DutyFinal,DutyStep):
    print('Duty Shift mode ON')
    
    for duty_shift_value in range(DutyInit, DutyFinal, DutyStep):  # Example values from ? to ? with a step of ?
      message1 = Board.sendCommand("DUTY", "LEG2", duty_shift_value/1000, delay=delay_com)
      print(f"Sent command with duty shift: {duty_shift_value/1000}, message: {message1}")

    for duty_shift_value_down in range(DutyFinal, DutyInit-DutyStep, -DutyStep):  # Example values from ? to ? with a step of ?
      message1 = Board.sendCommand("DUTY", "LEG2", duty_shift_value_down/1000, delay=delay_com)
      print(f"Sent command with phase shift: {duty_shift_value_down/1000}, message: {message1}")


# -------------------------------------------------
# PART 8: MAIN function
# -------------------------------------------------

def main():
    leg_to_test = "LEG1"                               #leg to be tested in this script
    reference_names = ["V1","V2","VH","I1","I2","IH"]  #names of the sensors of the board

    shield_vid = 0x2fe3
    shield_pid = 0x0101

    Shield_ports = find_devices.find_shield_device_ports(shield_vid, shield_pid)
    print(Shield_ports)

    Shield = Shield_Device(shield_port=Shield_ports[0], shield_type='TWIST')

    try:

      # ---------------HARDWARE IN THE LOOP PV EMULATOR CODE ------------------------------------
    ##  message1 = Shield.sendCommand("IDLE")
    ##  print(message1)
    ##
    ##  message = Shield.sendCommand( "BUCK", "LEG1", "OFF")
    ##  print(message)
    ##
    ##  message = Shield.sendCommand( "BUCK", "LEG2", "OFF")
    ##  print(message)

        message = Shield.sendCommand("LEG","LEG1","ON")
        print(message)

        message = Shield.sendCommand("LEG","LEG2","ON")
        print(message)

        message = Shield.sendCommand("POWER_ON")
        print(message)

        message = Shield.sendCommand("DUTY","LEG1",DutyPWM) # Initial duty cycle is 48.5%, to compensate dead time
        print(message)

        message = Shield.sendCommand("DUTY","LEG2",DutyPWM) # Initial duty cycle is 48.5%, to compensate dead time
        print(message)

    ##  for dead_time_value in range(100, 300, 50):
    ##      message1 = Shield.sendCommand("DEAD_TIME_RISING", "LEG1", dead_time_value)
    ##      message1 = Shield.sendCommand("DEAD_TIME_FALLING", "LEG1", dead_time_value)
    ##      message1 = Shield.sendCommand("DEAD_TIME_RISING", "LEG2", dead_time_value)
    ##      message1 = Shield.sendCommand("DEAD_TIME_FALLING", "LEG2", dead_time_value)
    ##      print(f"Sent command with phase shift: {dead_time_value}, message: {message1}")

    ##
    ##  for frequency_value in range(50000, 150000, 10000):  # Example values from 0 to 170 with a step of 10
    ##      message1 = Shield.sendCommand("FREQUENCY", "LEG1", frequency_value)
    ##      print(f"Sent command with frequency: {frequency_value}, message: {message1}")

        message1 = Shield.sendCommand("FREQUENCY", "LEG1", frequencyPWM) # 100 kHz switching freq


        message = Shield.sendCommand("DEAD_TIME_RISING","LEG2",DeadTimePWM) # 300 ns deadtime
        message = Shield.sendCommand("DEAD_TIME_RISING","LEG1",DeadTimePWM) # 300 ns deadtime
        print(message)

        message = Shield.sendCommand("DEAD_TIME_FALLING","LEG2",DeadTimePWM) # 300 ns deadtime
        message = Shield.sendCommand("DEAD_TIME_FALLING","LEG1",DeadTimePWM) # 300 ns deadtime
        print(message)


        message1 = Shield.sendCommand("PHASE_SHIFT","LEG2",InitialPhaseShiftPWM) # Initial phase shift is 15°
        print(message1)


        # Return to init Phase
        #message1 = Shield.sendCommand("PHASE_SHIFT", "LEG2", 10)
        #print(message1)

        #Turn OFF PWM signals
        #message = Shield.sendCommand( "LEG", "LEG1", "OFF")
        #print(message)
        ##
        #message = Shield.sendCommand( "LEG", "LEG2", "OFF")
        #print(message)

    finally:
        rm.close()
        print('Job Done!')


if __name__ == "__main__":

    print(rm.list_resources())
    
    main()
    # list_instruments()

    # dmm = openSiglentDMM('SDM36HCX800420')
    # print(dmm.resource_info.resource_name)
    # dmm.write('*RST')
    # dmm.write('INITiate')
